/*
Kpture-backend

Kpture Backend server

API version: 0.1
Contact: kpture.git@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// ServerKptureRequestAgentsRequestInner struct for ServerKptureRequestAgentsRequestInner
type ServerKptureRequestAgentsRequestInner struct {
	Name *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
}

// NewServerKptureRequestAgentsRequestInner instantiates a new ServerKptureRequestAgentsRequestInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerKptureRequestAgentsRequestInner() *ServerKptureRequestAgentsRequestInner {
	this := ServerKptureRequestAgentsRequestInner{}
	return &this
}

// NewServerKptureRequestAgentsRequestInnerWithDefaults instantiates a new ServerKptureRequestAgentsRequestInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerKptureRequestAgentsRequestInnerWithDefaults() *ServerKptureRequestAgentsRequestInner {
	this := ServerKptureRequestAgentsRequestInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ServerKptureRequestAgentsRequestInner) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerKptureRequestAgentsRequestInner) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ServerKptureRequestAgentsRequestInner) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ServerKptureRequestAgentsRequestInner) SetName(v string) {
	o.Name = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *ServerKptureRequestAgentsRequestInner) GetNamespace() string {
	if o == nil || o.Namespace == nil {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerKptureRequestAgentsRequestInner) GetNamespaceOk() (*string, bool) {
	if o == nil || o.Namespace == nil {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *ServerKptureRequestAgentsRequestInner) HasNamespace() bool {
	if o != nil && o.Namespace != nil {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *ServerKptureRequestAgentsRequestInner) SetNamespace(v string) {
	o.Namespace = &v
}

func (o ServerKptureRequestAgentsRequestInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Namespace != nil {
		toSerialize["namespace"] = o.Namespace
	}
	return json.Marshal(toSerialize)
}

type NullableServerKptureRequestAgentsRequestInner struct {
	value *ServerKptureRequestAgentsRequestInner
	isSet bool
}

func (v NullableServerKptureRequestAgentsRequestInner) Get() *ServerKptureRequestAgentsRequestInner {
	return v.value
}

func (v *NullableServerKptureRequestAgentsRequestInner) Set(val *ServerKptureRequestAgentsRequestInner) {
	v.value = val
	v.isSet = true
}

func (v NullableServerKptureRequestAgentsRequestInner) IsSet() bool {
	return v.isSet
}

func (v *NullableServerKptureRequestAgentsRequestInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerKptureRequestAgentsRequestInner(val *ServerKptureRequestAgentsRequestInner) *NullableServerKptureRequestAgentsRequestInner {
	return &NullableServerKptureRequestAgentsRequestInner{value: val, isSet: true}
}

func (v NullableServerKptureRequestAgentsRequestInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerKptureRequestAgentsRequestInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


