/*
Kpture-backend

Kpture Backend server

API version: 0.1
Contact: kpture.git@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// ServerKptureRequest struct for ServerKptureRequest
type ServerKptureRequest struct {
	AgentsRequest []ServerKptureRequestAgentsRequestInner `json:"agentsRequest,omitempty"`
	KptureName *string `json:"kptureName,omitempty"`
}

// NewServerKptureRequest instantiates a new ServerKptureRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerKptureRequest() *ServerKptureRequest {
	this := ServerKptureRequest{}
	return &this
}

// NewServerKptureRequestWithDefaults instantiates a new ServerKptureRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerKptureRequestWithDefaults() *ServerKptureRequest {
	this := ServerKptureRequest{}
	return &this
}

// GetAgentsRequest returns the AgentsRequest field value if set, zero value otherwise.
func (o *ServerKptureRequest) GetAgentsRequest() []ServerKptureRequestAgentsRequestInner {
	if o == nil || o.AgentsRequest == nil {
		var ret []ServerKptureRequestAgentsRequestInner
		return ret
	}
	return o.AgentsRequest
}

// GetAgentsRequestOk returns a tuple with the AgentsRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerKptureRequest) GetAgentsRequestOk() ([]ServerKptureRequestAgentsRequestInner, bool) {
	if o == nil || o.AgentsRequest == nil {
		return nil, false
	}
	return o.AgentsRequest, true
}

// HasAgentsRequest returns a boolean if a field has been set.
func (o *ServerKptureRequest) HasAgentsRequest() bool {
	if o != nil && o.AgentsRequest != nil {
		return true
	}

	return false
}

// SetAgentsRequest gets a reference to the given []ServerKptureRequestAgentsRequestInner and assigns it to the AgentsRequest field.
func (o *ServerKptureRequest) SetAgentsRequest(v []ServerKptureRequestAgentsRequestInner) {
	o.AgentsRequest = v
}

// GetKptureName returns the KptureName field value if set, zero value otherwise.
func (o *ServerKptureRequest) GetKptureName() string {
	if o == nil || o.KptureName == nil {
		var ret string
		return ret
	}
	return *o.KptureName
}

// GetKptureNameOk returns a tuple with the KptureName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerKptureRequest) GetKptureNameOk() (*string, bool) {
	if o == nil || o.KptureName == nil {
		return nil, false
	}
	return o.KptureName, true
}

// HasKptureName returns a boolean if a field has been set.
func (o *ServerKptureRequest) HasKptureName() bool {
	if o != nil && o.KptureName != nil {
		return true
	}

	return false
}

// SetKptureName gets a reference to the given string and assigns it to the KptureName field.
func (o *ServerKptureRequest) SetKptureName(v string) {
	o.KptureName = &v
}

func (o ServerKptureRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AgentsRequest != nil {
		toSerialize["agentsRequest"] = o.AgentsRequest
	}
	if o.KptureName != nil {
		toSerialize["kptureName"] = o.KptureName
	}
	return json.Marshal(toSerialize)
}

type NullableServerKptureRequest struct {
	value *ServerKptureRequest
	isSet bool
}

func (v NullableServerKptureRequest) Get() *ServerKptureRequest {
	return v.value
}

func (v *NullableServerKptureRequest) Set(val *ServerKptureRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableServerKptureRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableServerKptureRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerKptureRequest(val *ServerKptureRequest) *NullableServerKptureRequest {
	return &NullableServerKptureRequest{value: val, isSet: true}
}

func (v NullableServerKptureRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerKptureRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


