/*
Kpture-backend

Kpture Backend server

API version: 0.1
Contact: kpture.git@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// CaptureKpture struct for CaptureKpture
type CaptureKpture struct {
	Agents []AgentInfo `json:"agents,omitempty"`
	CaptureInfo *CaptureInfo `json:"captureInfo,omitempty"`
	Name *string `json:"name,omitempty"`
	ProfilName *string `json:"profilName,omitempty"`
	StartTime *int32 `json:"startTime,omitempty"`
	Status *string `json:"status,omitempty"`
	StopTime *int32 `json:"stopTime,omitempty"`
	Uuid *string `json:"uuid,omitempty"`
}

// NewCaptureKpture instantiates a new CaptureKpture object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCaptureKpture() *CaptureKpture {
	this := CaptureKpture{}
	return &this
}

// NewCaptureKptureWithDefaults instantiates a new CaptureKpture object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCaptureKptureWithDefaults() *CaptureKpture {
	this := CaptureKpture{}
	return &this
}

// GetAgents returns the Agents field value if set, zero value otherwise.
func (o *CaptureKpture) GetAgents() []AgentInfo {
	if o == nil || o.Agents == nil {
		var ret []AgentInfo
		return ret
	}
	return o.Agents
}

// GetAgentsOk returns a tuple with the Agents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaptureKpture) GetAgentsOk() ([]AgentInfo, bool) {
	if o == nil || o.Agents == nil {
		return nil, false
	}
	return o.Agents, true
}

// HasAgents returns a boolean if a field has been set.
func (o *CaptureKpture) HasAgents() bool {
	if o != nil && o.Agents != nil {
		return true
	}

	return false
}

// SetAgents gets a reference to the given []AgentInfo and assigns it to the Agents field.
func (o *CaptureKpture) SetAgents(v []AgentInfo) {
	o.Agents = v
}

// GetCaptureInfo returns the CaptureInfo field value if set, zero value otherwise.
func (o *CaptureKpture) GetCaptureInfo() CaptureInfo {
	if o == nil || o.CaptureInfo == nil {
		var ret CaptureInfo
		return ret
	}
	return *o.CaptureInfo
}

// GetCaptureInfoOk returns a tuple with the CaptureInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaptureKpture) GetCaptureInfoOk() (*CaptureInfo, bool) {
	if o == nil || o.CaptureInfo == nil {
		return nil, false
	}
	return o.CaptureInfo, true
}

// HasCaptureInfo returns a boolean if a field has been set.
func (o *CaptureKpture) HasCaptureInfo() bool {
	if o != nil && o.CaptureInfo != nil {
		return true
	}

	return false
}

// SetCaptureInfo gets a reference to the given CaptureInfo and assigns it to the CaptureInfo field.
func (o *CaptureKpture) SetCaptureInfo(v CaptureInfo) {
	o.CaptureInfo = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CaptureKpture) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaptureKpture) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CaptureKpture) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CaptureKpture) SetName(v string) {
	o.Name = &v
}

// GetProfilName returns the ProfilName field value if set, zero value otherwise.
func (o *CaptureKpture) GetProfilName() string {
	if o == nil || o.ProfilName == nil {
		var ret string
		return ret
	}
	return *o.ProfilName
}

// GetProfilNameOk returns a tuple with the ProfilName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaptureKpture) GetProfilNameOk() (*string, bool) {
	if o == nil || o.ProfilName == nil {
		return nil, false
	}
	return o.ProfilName, true
}

// HasProfilName returns a boolean if a field has been set.
func (o *CaptureKpture) HasProfilName() bool {
	if o != nil && o.ProfilName != nil {
		return true
	}

	return false
}

// SetProfilName gets a reference to the given string and assigns it to the ProfilName field.
func (o *CaptureKpture) SetProfilName(v string) {
	o.ProfilName = &v
}

// GetStartTime returns the StartTime field value if set, zero value otherwise.
func (o *CaptureKpture) GetStartTime() int32 {
	if o == nil || o.StartTime == nil {
		var ret int32
		return ret
	}
	return *o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaptureKpture) GetStartTimeOk() (*int32, bool) {
	if o == nil || o.StartTime == nil {
		return nil, false
	}
	return o.StartTime, true
}

// HasStartTime returns a boolean if a field has been set.
func (o *CaptureKpture) HasStartTime() bool {
	if o != nil && o.StartTime != nil {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given int32 and assigns it to the StartTime field.
func (o *CaptureKpture) SetStartTime(v int32) {
	o.StartTime = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CaptureKpture) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaptureKpture) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CaptureKpture) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CaptureKpture) SetStatus(v string) {
	o.Status = &v
}

// GetStopTime returns the StopTime field value if set, zero value otherwise.
func (o *CaptureKpture) GetStopTime() int32 {
	if o == nil || o.StopTime == nil {
		var ret int32
		return ret
	}
	return *o.StopTime
}

// GetStopTimeOk returns a tuple with the StopTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaptureKpture) GetStopTimeOk() (*int32, bool) {
	if o == nil || o.StopTime == nil {
		return nil, false
	}
	return o.StopTime, true
}

// HasStopTime returns a boolean if a field has been set.
func (o *CaptureKpture) HasStopTime() bool {
	if o != nil && o.StopTime != nil {
		return true
	}

	return false
}

// SetStopTime gets a reference to the given int32 and assigns it to the StopTime field.
func (o *CaptureKpture) SetStopTime(v int32) {
	o.StopTime = &v
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *CaptureKpture) GetUuid() string {
	if o == nil || o.Uuid == nil {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaptureKpture) GetUuidOk() (*string, bool) {
	if o == nil || o.Uuid == nil {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *CaptureKpture) HasUuid() bool {
	if o != nil && o.Uuid != nil {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *CaptureKpture) SetUuid(v string) {
	o.Uuid = &v
}

func (o CaptureKpture) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Agents != nil {
		toSerialize["agents"] = o.Agents
	}
	if o.CaptureInfo != nil {
		toSerialize["captureInfo"] = o.CaptureInfo
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.ProfilName != nil {
		toSerialize["profilName"] = o.ProfilName
	}
	if o.StartTime != nil {
		toSerialize["startTime"] = o.StartTime
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.StopTime != nil {
		toSerialize["stopTime"] = o.StopTime
	}
	if o.Uuid != nil {
		toSerialize["uuid"] = o.Uuid
	}
	return json.Marshal(toSerialize)
}

type NullableCaptureKpture struct {
	value *CaptureKpture
	isSet bool
}

func (v NullableCaptureKpture) Get() *CaptureKpture {
	return v.value
}

func (v *NullableCaptureKpture) Set(val *CaptureKpture) {
	v.value = val
	v.isSet = true
}

func (v NullableCaptureKpture) IsSet() bool {
	return v.isSet
}

func (v *NullableCaptureKpture) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCaptureKpture(val *CaptureKpture) *NullableCaptureKpture {
	return &NullableCaptureKpture{value: val, isSet: true}
}

func (v NullableCaptureKpture) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCaptureKpture) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


