apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proxy
rules:
- apiGroups: ["","admissionregistration.k8s.io",]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "watch", "list","create","update","delete"]
- apiGroups: ["","events.k8s.io","apps"]
  resources: ["pods","services"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kpture-rbac-devspace
subjects:
- kind: ServiceAccount
  name: {{ include "tls.serviceAccountName" . }}
  namespace: {{.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: proxy
  apiGroup: rbac.authorization.k8s.io