apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kpture.serviceAccountName" . }}
  labels:
    {{- include "kpture.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
