apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: kpture-webhook-mutation
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: "${CA_BUNDLE}"
    service:
      name: tls
      namespace: kpture
      path: /mutate
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: injection.kpture.io
  namespaceSelector:
    matchLabels:
      kpture-agent: enabled
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10