definitions:
  agent.AgentInfo:
    properties:
      name:
        type: string
      namespace:
        type: string
      targetUrl:
        type: string
      type:
        type: string
    type: object
  capture.CaptureInfo:
    properties:
      packet_nb:
        type: integer
      size:
        type: integer
    type: object
  capture.Kpture:
    properties:
      capture_info:
        $ref: '#/definitions/capture.CaptureInfo'
      name:
        type: string
      status:
        type: string
      uuid:
        type: string
    type: object
  server.KptureRequest:
    properties:
      agents:
        items:
          properties:
            name:
              type: string
            namespace:
              type: string
          type: object
        type: array
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: kpture.git@gmail.com
    name: Author
    url: http://www.kpture.io
  description: Kpture Backend server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Kpture-backend
  version: "0.1"
paths:
  /api/v1/agents:
    get:
      description: Get Agents
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/agent.AgentInfo'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get Agents
      tags:
      - agents
  /api/v1/kpture:
    post:
      consumes:
      - application/json
      description: Start Kpture
      parameters:
      - description: selected agents for capture
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/server.KptureRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Websocket:
              type: string
          schema:
            $ref: '#/definitions/capture.Kpture'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Start Kpture
      tags:
      - kptures
  /api/v1/kpture/{uuid}:
    get:
      description: get K8S capture
      parameters:
      - description: capture uuid
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/capture.Kpture'
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: get K8S capture
      tags:
      - kptures
  /api/v1/kpture/{uuid}/download:
    get:
      description: Download Kpture
      parameters:
      - description: capture uuid
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Download Kpture
      tags:
      - kptures
  /api/v1/kpture/{uuid}/stop:
    put:
      description: Stop Kpture
      parameters:
      - description: capture uuid
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/capture.Kpture'
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Stop Kpture
      tags:
      - kptures
  /api/v1/kptures:
    get:
      description: get K8S capture
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              $ref: '#/definitions/capture.Kpture'
            type: object
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: get K8S capture
      tags:
      - kptures
swagger: "2.0"
