name: Golang test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: install libpcap
      run: sudo apt-get install libpcap-dev
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Build test
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: false