
name: Create Release
on: [workflow_dispatch]
jobs:
  build:
    uses: ./.github/workflows/build.yml
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Bump version and push tag
        id: bumptag
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: "main"
          DRY_RUN: "true"
          DEFAULT_BUMP : "patch"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      - name: Build
        run: |
          docker build . --platform=linux/amd64,linux/arm64 -t kpture:${{ steps.bumptag.outputs.new_tag }} --push
      - name: Release Changelog Builder
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3.0.1
      - name: Package and upload helm chart
        run: |
          tag=${{ steps.bumptag.outputs.new_tag }}
          #Download yq
          wget -qO ./yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod a+x ./yq
          ./yq e '.appVersion = "latest" ' -i chart/Chart.yaml
          ./yq e '.version = "latest" ' -i chart/Chart.yaml
          ./yq e ".dependencies[0].version = \"$tag\" " -i chart/Chart.yaml
          # donwload helm chart releaser
          curl -sSLo cr.tar.gz "https://github.com/helm/chart-releaser/releases/download/v1.2.1/chart-releaser_1.2.1_linux_amd64.tar.gz"
          tar -xzf cr.tar.gz
          rm -f cr.tar.gz
          owner=$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")
          repo=$(cut -d '/' -f 2 <<< "$GITHUB_REPOSITORY")
          # package chart
          ./cr package chart
          # upload chart to github relases
          ./cr upload \
              --owner "$owner" \
              --git-repo "$repo" \
              --token "${{ secrets.GITHUB_TOKEN }}" \
              --release-name-template "{{ .Version }}"
          # update index and push to github pages
          git config user.email "$owner@users.noreply.github.com"
          git config user.name "$owner"
          ./cr index \
              --owner "$owner" \
              --git-repo "$repo" \
              --token "${{ secrets.GITHUB_TOKEN }}" \
              --release-name-template "{{ .Version }}" \
              --release-notes-file ${{steps.build_changelog.outputs.changelog}} \
              --index-path ./index.yaml \
              --charts-repo https://$owner.github.io/$repo \
              --push
